fix: The error "TypeError: node.type.spec.toDOM is not a function"
- means that some nodes in the ProseMirror schema are missing the toDOM method, which is necessary for rendering them into the DOM.

- need to add toDOM properties to all the nodes in packages/editor-core/src/index.ts to define how they should be rendered as HTML
  elements.